FROM kuklusklan/ubbase

USER root
RUN apt update && apt install -yq --no-install-recommends \
    nginx

RUN chown -R www-data /var/www/html
RUN chmod -R 755 /var/www/html

# Instalo nginx/apache --> usuario www-data
# El propietario de /var/www/html es www-data
RUN mkdir -p /var/log/nginx
EXPOSE 80

RUN mkdir -p /root/admin/nginx
COPY ./dockerfile/sweb/nginx/admin /root/admin/nginx
RUN chmod +x /root/admin/sweb/nginx/start.sh
WORKDIR /root/admin/nginx
ENTRYPOINT [ "./start.sh" ]